name: Benchmark Tracking
on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/Benchmarks.yaml'
      - 'src/**'
      - 'ext/**'
      - 'benchmark/**'
      - 'test/runtests.jl'
      - 'Project.toml'
  pull_request:
    paths:
      - '.github/workflows/Benchmarks.yaml'
      - 'src/**'
      - 'ext/**'
      - 'test/**'
      - 'benchmark/**'
      - 'Project.toml'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
    actions: write
    contents: write
    deployments: write
    pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1.12'
          arch: x64
      - uses: julia-actions/cache@v3
      - name: Run benchmarks
        run: |
          cd benchmark
          julia --project --threads=2 --color=yes -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=joinpath(pwd(), "..")));
            Pkg.instantiate();
            include("runbenchmarks.jl")'

      # this will update benchmark/data.js in gh-pages branch
      - name: Parse & Upload Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark Results
          tool: "julia"
          output-file-path: benchmark/benchmarks_output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: "130%"
          fail-threshold: "170%"
          comment-on-alert: true
          fail-on-alert: true
          benchmark-data-dir-path: benchmark
          max-items-in-chart: 100
          auto-push: ${{ github.event_name != 'pull_request' }}
