name: Tests

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Tests.yml'
      - 'src/**'
      - 'ext/**'
      - 'test/**'
      - 'Project.toml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Tests.yml'
      - 'src/**'
      - 'ext/**'
      - 'test/**'
      - 'Project.toml'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

env:
  JULIA_NUM_THREADS: 11

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 300
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'pre'
          - 'lts'
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v2
        with:
          show-versioninfo: true
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
          name: codecov-umbrella
          fail_ci_if_error: false
        if: ${{ matrix.version == 'lts' }}
